name: Release website to github pages and buckets

on:
  push:
    branches:
      # - release/3.10  # Set a branch to deploy
      # - release/*  # Set a branch to deploy
      - main  # Set a branch to deploy
      - fix-.*
    tags:
      - v3.*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: yarn

    - name: "Install dependencies"
      shell: bash
      run: |
        echo $PWD
        echo $GITHUB_WORKSPACE
        cd /home/runner/work/website/website
        yarn install --frozen-lockfile

    - name: Build public site
      shell: bash
      run: |
        echo $PWD
        echo $GITHUB_WORKSPACE
        yarn build

    - name: Publish site to yunionio/yunionio.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./build
        external_repository: yunionio/yunionio.github.io
        allow_empty_commit: true
        cname: www.cloudpods.org
        publish_branch: master

    - name: Publish site to AWS s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # deploy config
        AWS_REGION: 'ap-east-1'
        SOURCE_DIR: 'build'
